[package]
name = "gl-tests-god-save-me"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
nalgebra-glm = "0.19.0"

[dev-dependencies]
sdl2 = { version = "0.37.0", features = ["use-pkgconfig", "static-link"] }
